//! Per-library document store: the documents table and `raw/` files of one
//! content library, plus the derived `index.md`, `manifest.json` and the
//! content full-text index.

use std::{fs, path::Path};

use chrono::Utc;
use rusqlite::{Connection, OptionalExtension, params};
use sha2::{Digest, Sha256};
use uuid::Uuid;
use walkdir::WalkDir;

use super::{
    DocumentRecord, Storage, StoredDocument, fsutil::write_atomic, parse_timestamp_or_now,
};
use crate::error::AppError;

impl Storage {
    pub fn store_document(
        &self,
        library_id: &str,
        filename: &str,
        title: Option<&str>,
        content: &str,
    ) -> Result<StoredDocument, AppError> {
        let root = self.library_root(library_id)?;
        validate_filename(filename)?;
        let mut hasher = Sha256::new();
        hasher.update(content.as_bytes());
        let sha256 = hex::encode(hasher.finalize());
        let now = Utc::now();
        let connection = Connection::open(root.join("library.sqlite"))?;

        if let Some(existing) = connection
            .query_row(
                "SELECT id, filename, title, path, sha256, created_at FROM documents WHERE sha256 = ?1",
                params![sha256],
                document_from_row,
            )
            .optional()?
        {
            return Ok(StoredDocument {
                record: existing,
                duplicate: true,
            });
        }

        let id = Uuid::new_v4().to_string();
        let safe_name = format!("{}-{}", &sha256[..12], filename);
        let relative_path = format!("raw/{safe_name}");
        write_atomic(&root.join(&relative_path), content.as_bytes())?;
        let record = DocumentRecord {
            id,
            filename: filename.into(),
            title: title
                .filter(|value| !value.trim().is_empty())
                .map(ToOwned::to_owned)
                .unwrap_or_else(|| {
                    Path::new(filename)
                        .file_stem()
                        .and_then(|value| value.to_str())
                        .unwrap_or(filename)
                        .to_string()
                }),
            path: relative_path,
            sha256,
            created_at: now,
        };
        connection.execute(
            "INSERT INTO documents (id, filename, title, path, sha256, created_at) VALUES (?1, ?2, ?3, ?4, ?5, ?6)",
            params![
                record.id,
                record.filename,
                record.title,
                record.path,
                record.sha256,
                record.created_at.to_rfc3339(),
            ],
        )?;
        self.write_manifest(library_id)?;
        Ok(StoredDocument {
            record,
            duplicate: false,
        })
    }

    pub fn write_manifest(&self, library_id: &str) -> Result<(), AppError> {
        let root = self.library_root(library_id)?;
        let connection = Connection::open(root.join("library.sqlite"))?;
        let mut statement = connection.prepare(
            "SELECT id, filename, title, path, sha256, created_at FROM documents ORDER BY created_at",
        )?;
        let documents = statement
            .query_map([], document_from_row)?
            .collect::<Result<Vec<_>, _>>()?;
        let manifest = serde_json::json!({ "documents": documents });
        write_atomic(
            &root.join("manifest.json"),
            serde_json::to_vec_pretty(&manifest)?.as_slice(),
        )?;
        Ok(())
    }

    pub fn rebuild_index(&self, library_id: &str) -> Result<(), AppError> {
        let root = self.library_root(library_id)?;
        let mut output = String::from("# Knowledge Library Index\n\n");
        output.push_str("This file is generated by Noema and is a navigation aid.\n\n");
        for (label, directory, extensions) in [
            ("Sources", "raw", &["md", "txt"] as &[&str]),
            ("Knowledge nodes", "wiki", &["md"] as &[&str]),
        ] {
            output.push_str(&format!("## {label}\n\n"));
            let directory_path = root.join(directory);
            let mut paths = Vec::new();
            if directory_path.exists() {
                for entry in WalkDir::new(&directory_path).follow_links(false) {
                    let entry = entry?;
                    if entry.file_type().is_file()
                        && entry
                            .path()
                            .extension()
                            .and_then(|value| value.to_str())
                            .is_some_and(|extension| extensions.contains(&extension))
                    {
                        paths.push(entry.path().to_path_buf());
                    }
                }
            }
            paths.sort();
            for path in paths {
                let relative = path.strip_prefix(&root)?.display();
                output.push_str(&format!("- `{relative}`\n"));
            }
            output.push('\n');
        }
        write_atomic(&root.join("index.md"), output.as_bytes())?;
        rebuild_content_fts(&root)?;
        self.write_manifest(library_id)
    }
}

pub(super) fn init_library_db(path: &Path) -> Result<(), AppError> {
    let connection = Connection::open(path)?;
    connection.execute_batch(
        "
        PRAGMA foreign_keys = ON;
        CREATE TABLE IF NOT EXISTS documents (
            id TEXT PRIMARY KEY,
            filename TEXT NOT NULL,
            title TEXT NOT NULL,
            path TEXT NOT NULL UNIQUE,
            sha256 TEXT NOT NULL UNIQUE,
            created_at TEXT NOT NULL
        );
        CREATE TABLE IF NOT EXISTS nodes (
            node_id TEXT PRIMARY KEY,
            path TEXT NOT NULL UNIQUE,
            canonical_name TEXT NOT NULL,
            updated_at TEXT NOT NULL
        );
        CREATE VIRTUAL TABLE IF NOT EXISTS content_fts USING fts5(path, title, body);
        ",
    )?;
    Ok(())
}

fn rebuild_content_fts(root: &Path) -> Result<(), AppError> {
    let connection = Connection::open(root.join("library.sqlite"))?;
    connection.execute("DELETE FROM content_fts", [])?;

    for directory in ["raw", "wiki"] {
        let directory_path = root.join(directory);
        if !directory_path.exists() {
            continue;
        }
        for entry in WalkDir::new(&directory_path).follow_links(false) {
            let entry = entry?;
            if !entry.file_type().is_file() {
                continue;
            }
            let extension = entry
                .path()
                .extension()
                .and_then(|value| value.to_str())
                .unwrap_or_default();
            let allowed = if directory == "raw" {
                extension.eq_ignore_ascii_case("md") || extension.eq_ignore_ascii_case("txt")
            } else {
                extension.eq_ignore_ascii_case("md")
            };
            if !allowed {
                continue;
            }
            let body = fs::read_to_string(entry.path())?;
            let relative = entry.path().strip_prefix(root)?.display().to_string();
            let title = entry
                .path()
                .file_stem()
                .and_then(|value| value.to_str())
                .unwrap_or_default();
            connection.execute(
                "INSERT INTO content_fts (path, title, body) VALUES (?1, ?2, ?3)",
                params![relative, title, body],
            )?;
        }
    }
    Ok(())
}

fn document_from_row(row: &rusqlite::Row<'_>) -> rusqlite::Result<DocumentRecord> {
    let created_at: String = row.get(5)?;
    Ok(DocumentRecord {
        id: row.get(0)?,
        filename: row.get(1)?,
        title: row.get(2)?,
        path: row.get(3)?,
        sha256: row.get(4)?,
        created_at: parse_timestamp_or_now(&created_at),
    })
}

fn validate_filename(value: &str) -> Result<(), AppError> {
    let path = Path::new(value);
    let extension = path
        .extension()
        .and_then(|value| value.to_str())
        .unwrap_or_default();
    if value.is_empty()
        || value.contains('/')
        || value.contains('\\')
        || value == "."
        || value == ".."
        || !matches!(extension.to_ascii_lowercase().as_str(), "md" | "txt")
    {
        return Err(AppError::BadRequest(
            "filename must be a single .md or .txt filename".into(),
        ));
    }
    Ok(())
}
